Repository woowa-techcamp-2021/baemin-19, pull requests merged in 2021-07, with the labels that each got.

#5 Develop basic codes on server end point
  .gitignore
  package.json
  server/index.js
  server/views/index.pug
  yarn.lock
Labels: setting

#10 기본 레이아웃 설정 및 스타일링
  client/assets/css/index.css
  client/assets/css/login.css
  client/assets/css/reset.css
  client/assets/icons/check.svg
  client/assets/icons/left.svg
  client/assets/icons/x.svg
  client/assets/js/index.js
  client/index.html
Labels: enhancement

#11 회원가입 페이지 레이아웃 설정 및 스타일링
  client/assets/css/component/checkbox.css
  client/assets/css/component/form_element.css
  client/assets/css/component/header.css
  client/assets/css/component/radio.css
  client/assets/css/index.css
  client/assets/css/phone.css
  client/assets/css/rest.css
  client/assets/css/terms.css
  client/signup_phone.html
  client/signup_rest.html
  client/signup_terms.html
Labels: enhancement

#12 메인 페이지 레이아웃 설정 및 스타일링
  client/assets/css/component/header.css
  client/assets/css/main.css
  client/assets/icons/coupon.png
  client/assets/icons/gift.png
  client/assets/icons/like.png
  client/assets/icons/order.png
  client/assets/icons/point.png
  client/assets/icons/review.png
  client/assets/icons/user.png
  client/index.html
  client/login.html
Labels: enhancement

#22 Move static files into server
  client/index.html
  client/login.html
  client/signup_phone.html
  client/signup_rest.html
  client/signup_terms.html
  server/assets/css/component/checkbox.css
  server/assets/css/component/form_element.css
  server/assets/css/component/header.css
  server/assets/css/component/radio.css
  server/assets/css/index.css
  server/assets/css/login.css
  server/assets/css/main.css
  server/assets/css/phone.css
  server/assets/css/reset.css
  server/assets/css/rest.css
  server/assets/css/terms.css
  server/assets/icons/check.svg
  server/assets/icons/coupon.png
  server/assets/icons/gift.png
  server/assets/icons/left.svg
  server/assets/icons/like.png
  server/assets/icons/order.png
  server/assets/icons/point.png
  server/assets/icons/review.png
  server/assets/icons/user.png
  server/assets/icons/x.svg
  server/assets/js/index.js
  server/index.js
  server/views/index.pug
  server/views/login.pug
  server/views/signup_phone.pug
  server/views/signup_rest.pug
  server/views/signup_terms.pug
Labels: feature

#24 Add logic of terms, login page
  server/assets/css/component/header.css
  server/assets/css/index.css
  server/assets/css/login.css
  server/assets/css/terms.css
  server/assets/icons/logo.png
  server/assets/js/login.js
  server/assets/js/signup_terms.js
  server/assets/js/utils/checkValidation.js
  server/assets/js/utils/selector.js
  server/views/login.pug
  server/views/signup_terms.pug
Labels: enhancement, feature

#29 Back-end 구현
  .gitignore
  package.json
  server/assets/css/reset.css
  server/assets/js/api/api.js
  server/assets/js/index.js
  server/assets/js/login.js
  server/assets/js/signup_rest.js
  server/db/db.json
  server/index.js
  server/models/store.js
  server/routes/authRouter.js
  server/routes/homeRouter.js
  server/routes/signupRouter.js
  server/views/index.pug
  server/views/login.pug
  server/views/signup_rest.pug
  server/views/signup_terms.pug
  yarn.lock
Labels: enhancement, feature

#30 feat: Hash password
  server/assets/js/signup_rest.js
  server/db/db.json
  server/routes/authRouter.js
  server/routes/signupRouter.js
  server/views/signup_rest.pug
Labels: enhancement

#32 Add Loading spinner
  server/assets/css/component/loadingSpinner.css
  server/assets/css/index.css
  server/assets/icons/spinner.png
  server/assets/js/login.js
  server/assets/js/utils/triggerSpinner.js
  server/views/login.pug
Labels: enhancement, feature

#34 Refactoring Backend Codes and Add 404 page
  server/assets/css/404page.css
  server/assets/icons/404-bg.png
  server/assets/icons/404-title.png
  server/assets/icons/404-to-home.png
  server/assets/js/utils/checkValidation.js
  server/index.js
  server/routes/authRouter.js
  server/routes/homeRouter.js
  server/routes/signupRouter.js
  server/views/404page.pug
  server/views/login.pug
Labels: enhancement
